config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :degreeprograms
  resources :subdisciplines
  resources :cities
  resources :discipline_universities
  resources :disciplines
  resources :universities
  root to: "disciplines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discipline.rb
class Discipline < ApplicationRecord
	resourcify
	# before_action :signed_in_user, only: [:edit, :update]
	validates :Name, :uniqueness => {:message => 'already taken'}

	has_many :discipline_university
	has_many :university, :through => :discipline_university
	has_many :subdisciplines, :through => :subdisciplines 
	# foreign_key: "id"
	has_many :degreeprogram, :through => :discipline_university
end

app/controllers/disciplines_controller.rb
class DisciplinesController < ApplicationController
  # before_filter :authenticate_user!
  before_action :set_discipline, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /disciplines
  # GET /disciplines.json
  def index
    @disciplines = Discipline.all
  end

  # GET /disciplines/1
  # GET /disciplines/1.json
  def show
     @degrees = @discipline.degreeprogram.distinct

    # @university = @discipline.university
    @sub = Subdiscipline.where(discipline_id:@discipline.id)
    # puts "asdas",@sub
  end

  # GET /disciplines/new
  def new
    @discipline = Discipline.new
  end

  # GET /disciplines/1/edit
  def edit
  end

  # POST /disciplines
  # POST /disciplines.json
  def create
    @discipline = Discipline.new(discipline_params)
    # puts @discipline.save

    respond_to do |format|
      if @discipline.save
        # puts "here"
        format.html { redirect_to @discipline, notice: 'Discipline was successfully created.' }
        format.json { render :show, status: :created, location: @discipline }
      else
        format.html { render :new }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disciplines/1
  # PATCH/PUT /disciplines/1.json
  def update
    respond_to do |format|
      if @discipline.update(discipline_params)
        format.html { redirect_to @discipline, notice: 'Discipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @discipline }
      else
        format.html { render :edit }
        format.json { render json: @discipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disciplines/1
  # DELETE /disciplines/1.json
  def destroy
    @discipline.destroy
    respond_to do |format|
      format.html { redirect_to disciplines_url, notice: 'Discipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discipline
      @discipline = Discipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discipline_params
      params.require(:discipline).permit(:Name, :Description)
    end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_form.html.erb
<%= form_for(discipline) do |f| %>
  <% if discipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discipline.errors.count, "error") %> prohibited this discipline from being saved:</h2>

      <ul>
      <% discipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Description %>
    <%= f.text_area :Description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disciplines/edit.html.erb
<h1>Editing Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Show', @discipline %> |
<%= link_to 'Back', disciplines_path %>

app/views/disciplines/index.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="container"> -->
<h1>Disciplines</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @disciplines.each do |discipline| %>
      <tr>
        <td><%= link_to discipline.Name, discipline %></td>
        <% if can? :update, discipline %>
        <td><%= link_to 'Edit', edit_discipline_path(discipline) %></td>
        <% end %>
        <% if can? :delete, discipline %>

        <td><%= link_to 'Destroy', discipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Discipline %>
<%= link_to 'New Discipline', new_discipline_path %>
<!-- </div> -->
<% end %>

app/views/disciplines/new.html.erb
<h1>New Discipline</h1>

<%= render 'form', discipline: @discipline %>

<%= link_to 'Back', disciplines_path %>

app/views/disciplines/show.html.erb
<p id="notice"><%= notice %></p>
<!-- <div class="container"> -->
<div class="row">
    <!-- <div class="col-md-2">col-md-3</div> -->
    <div class="col-md-8 col-md-offset-2">
      <p class="text-center">
        <h1 align="center"><%= @discipline.Name %></h1>
      </p>

      <p class="text-center">
        <!-- <strong>Description:</strong> -->
        <%= @discipline.Description %>
      </p>

      <p>
        <h2 align="center">Degrees offered</h2>
          <ul> <% for item in @degrees %>
            <% for uni in item.university %>
                <li> 
                  <%= item.name  %> by <%= uni.name %>
                </li>
            <% end %>
          <% end %>
          </ul>     
      </p>

    <p>
      <h2 align="center">Subdisciplines</h2>
          <ul> 
          <% for item in @sub %>
          <li>
          <%= link_to item.name,subdiscipline_path(item) %> </li>

          <% end %>
        </ul>

    </p>
    <% if can? :update, @discipline %>


    <%= link_to 'Edit', edit_discipline_path(@discipline) %>| 
    <% end %> 
    
    <%= link_to 'Back', disciplines_path %>
    </div>

  
  <!-- <div class="col-md-4">col-md-4</div> -->
</div>

<!-- </div> -->