config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :degreeprograms
  resources :subdisciplines
  resources :cities
  resources :discipline_universities
  resources :disciplines
  resources :universities
  root to: "disciplines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/degreeprogram.rb
class Degreeprogram < ApplicationRecord
	resourcify
	belongs_to :discipline
	belongs_to :subdiscipline
	# has_many :university_degree
	has_many :discipline_university
	has_many :university, :through => :discipline_university
	# validates_uniqueness_of :name, scope: [:degree_type, :subdiscipline_id,:discipline_id]
end

app/controllers/degreeprograms_controller.rb
class DegreeprogramsController < ApplicationController
  before_action :set_degreeprogram, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /degreeprograms
  # GET /degreeprograms.json
  def index
    @degreeprograms = Degreeprogram.all
  end

  # GET /degreeprograms/1
  # GET /degreeprograms/1.json
  def show
  end

  # GET /degreeprograms/new
  def new
    @degreeprogram = Degreeprogram.new
  end

  # GET /degreeprograms/1/edit
  def edit
  end

  # POST /degreeprograms
  # POST /degreeprograms.json
  def create
    @degreeprogram = Degreeprogram.new(degreeprogram_params)

    respond_to do |format|
      if @degreeprogram.save
        format.html { redirect_to @degreeprogram, notice: 'Degreeprogram was successfully created.' }
        format.json { render :show, status: :created, location: @degreeprogram }
      else
        format.html { render :new }
        format.json { render json: @degreeprogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /degreeprograms/1
  # PATCH/PUT /degreeprograms/1.json
  def update
    respond_to do |format|
      if @degreeprogram.update(degreeprogram_params)
        format.html { redirect_to @degreeprogram, notice: 'Degreeprogram was successfully updated.' }
        format.json { render :show, status: :ok, location: @degreeprogram }
      else
        format.html { render :edit }
        format.json { render json: @degreeprogram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /degreeprograms/1
  # DELETE /degreeprograms/1.json
  def destroy
    @degreeprogram.destroy
    respond_to do |format|
      format.html { redirect_to degreeprograms_url, notice: 'Degreeprogram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_degreeprogram
      @degreeprogram = Degreeprogram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def degreeprogram_params
      params.require(:degreeprogram).permit(:degree_type, :name, :subdiscipline_id, :discipline_id)
    end
end

app/helpers/degreeprograms_helper.rb
module DegreeprogramsHelper
end

app/views/degreeprograms/_form.html.erb
<%= form_for(degreeprogram) do |f| %>
  <% if degreeprogram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(degreeprogram.errors.count, "error") %> prohibited this degreeprogram from being saved:</h2>

      <ul>
      <% degreeprogram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :degree_type %>
    <%= f.select :degree_type,[["Bachelors","Bachelors"],["Masters","Masters"],["Phd","Phd"]] %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :subdiscipline_id %>
    <%= f.collection_select :subdiscipline_id, Subdiscipline.all,:id,:name %>
  </div>

  <div class="field">
      <%= f.label :discipline_id %>
      <%= f.collection_select :discipline_id, Discipline.all,:id,:Name %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/degreeprograms/edit.html.erb
<h1>Editing Degreeprogram</h1>

<%= render 'form', degreeprogram: @degreeprogram %>

<%= link_to 'Show', @degreeprogram %> |
<%= link_to 'Back', degreeprograms_path %>

app/views/degreeprograms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Degreeprograms</h1>

<table class="table">
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @degreeprograms.each do |degreeprogram| %>
      <tr>
        <td><%= degreeprogram.degree_type %></td>
        <td><%= degreeprogram.name %></td>
        <td><%= link_to 'Show', degreeprogram %></td>
        <td><%= link_to 'Edit', edit_degreeprogram_path(degreeprogram) %></td>
        <td><%= link_to 'Destroy', degreeprogram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Degreeprogram', new_degreeprogram_path %>

app/views/degreeprograms/new.html.erb
<h1>New Degreeprogram</h1>

<%= render 'form', degreeprogram: @degreeprogram %>

<%= link_to 'Back', degreeprograms_path %>

app/views/degreeprograms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @degreeprogram.degree_type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @degreeprogram.name %>
</p>

<%= link_to 'Edit', edit_degreeprogram_path(@degreeprogram) %> |
<%= link_to 'Back', degreeprograms_path %>