config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :degreeprograms
  resources :subdisciplines
  resources :cities
  resources :discipline_universities
  resources :disciplines
  resources :universities
  root to: "disciplines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subdiscipline.rb
class Subdiscipline < ApplicationRecord
  resourcify
  validates :name, :uniqueness => {:message => 'already taken'}
  belongs_to :discipline
  # has_many :degreeprogram
  has_many :univeristy,:through => :discipline_university
  has_many :degreeprogram
end

app/controllers/subdisciplines_controller.rb
class SubdisciplinesController < ApplicationController
  before_action :set_subdiscipline, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /subdisciplines
  # GET /subdisciplines.json
  def index
    @subdisciplines = Subdiscipline.all
  end

  # GET /subdisciplines/1
  # GET /subdisciplines/1.json
  def show
    @degree = @subdiscipline.degreeprogram.distinct
  end

  # GET /subdisciplines/new
  def new
    @subdiscipline = Subdiscipline.new
  end

  # GET /subdisciplines/1/edit
  def edit
  end

  # POST /subdisciplines
  # POST /subdisciplines.json
  def create
    @subdiscipline = Subdiscipline.new(subdiscipline_params)

    respond_to do |format|
      if @subdiscipline.save
        format.html { redirect_to @subdiscipline, notice: 'Subdiscipline was successfully created.' }
        format.json { render :show, status: :created, location: @subdiscipline }
      else
        format.html { render :new }
        format.json { render json: @subdiscipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subdisciplines/1
  # PATCH/PUT /subdisciplines/1.json
  def update
    respond_to do |format|
      if @subdiscipline.update(subdiscipline_params)
        format.html { redirect_to @subdiscipline, notice: 'Subdiscipline was successfully updated.' }
        format.json { render :show, status: :ok, location: @subdiscipline }
      else
        format.html { render :edit }
        format.json { render json: @subdiscipline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subdisciplines/1
  # DELETE /subdisciplines/1.json
  def destroy
    @subdiscipline.destroy
    respond_to do |format|
      format.html { redirect_to subdisciplines_url, notice: 'Subdiscipline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subdiscipline
      @subdiscipline = Subdiscipline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subdiscipline_params
      params.require(:subdiscipline).permit(:name, :discipline_id, :description)
    end
end

app/helpers/subdisciplines_helper.rb
module SubdisciplinesHelper
end

app/views/subdisciplines/_form.html.erb
<%= form_for(subdiscipline) do |f| %>
  <% if subdiscipline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subdiscipline.errors.count, "error") %> prohibited this subdiscipline from being saved:</h2>

      <ul>
      <% subdiscipline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :discipline_id %>
    <%= f.collection_select :discipline_id, Discipline.all,:id,:Name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subdisciplines/edit.html.erb
<h1>Editing Subdiscipline</h1>

<%= render 'form', subdiscipline: @subdiscipline %>

<%= link_to 'Show', @subdiscipline %> |
<%= link_to 'Back', subdisciplines_path %>

app/views/subdisciplines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subdisciplines</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Discipline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subdisciplines.each do |subdiscipline| %>
      <tr>
        <td><%= subdiscipline.name %></td>
        <td><%= subdiscipline.discipline.Name %></td>
        <td><%= link_to 'Show', subdiscipline %></td>
        <td><%= link_to 'Edit', edit_subdiscipline_path(subdiscipline) %></td>
        <td><%= link_to 'Destroy', subdiscipline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subdiscipline', new_subdiscipline_path %>

app/views/subdisciplines/new.html.erb
<h1>New Subdiscipline</h1>

<%= render 'form', subdiscipline: @subdiscipline %>

<%= link_to 'Back', subdisciplines_path %>

app/views/subdisciplines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subdiscipline.name %>
</p>

<p>
  <strong>Discipline:</strong>
  <%= @subdiscipline.discipline.Name %>
</p>

<p>
  <strong>Degrees in <%=@subdiscipline.name %>:</strong>
  <ul>
  <% for degree in @degree %>
  <% for uni in degree.university %>
  	<li>
  		<%= degree.name%> by <%= uni.name%>
  	</li>
  	<% end %>
  	<% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_subdiscipline_path(@subdiscipline) %> |
<%= link_to 'Back', subdisciplines_path %>